export const environment = {
  SQL_HOST: `${process.env.SQL_HOST}`,
  SQL_PASSWORD: `${process.env.SQL_PASSWORD}`,
  SQL_USER: `${process.env.SQL_USER}`,
  SQL_DATABASE: `${process.env.SQL_DATABASE}`,

  TRANSBANK_URL_V1: `${process.env.TRANSBANK_URL_V1}`,
  TRANSBANK_TBK_API_KEY_ID: `${process.env.TRANSBANK_TBK_API_KEY_ID}`,
  TRANSBANK_TBK_API_KEY_SECRET: `${process.env.TRANSBANK_TBK_API_KEY_SECRET}`,
  TRANSBANK_CONTENT_TYPE: `${process.env.TRANSBANK_CONTENT_TYPE}`,

  URL_CASTOR: `${process.env.URL_CASTOR}`,

  FIREBASE_CASTOR: `${process.env.FIREBASE_CASTOR}`,
  PATH_FIREBASE_CASTOR: `${process.env.PATH_FIREBASE_CASTOR}`,

  MSN_NOTIF_TASKS_UPDATE: `${process.env.MSN_NOTIF_TASKS_UPDATE}`,
  MSN_NOTIF_TASKS_DELETE: `${process.env.MSN_NOTIF_TASKS_DELETE}`,
  MSN_NOTIF_TASKS_INSERT: `${process.env.MSN_NOTIF_TASKS_INSERT}`,
  MSN_NOTIF_BIRTHDAYS: `${process.env.MSN_NOTIF_BIRTHDAYS}`,

  CRON_EXPRESSION_BIRTHDAYS: `${process.env.CRON_EXPRESSION_BIRTHDAYS}`,
  
  MAILER_USER: `${process.env.MAILER_USER}`,
  MAILER_PASS: `${process.env.MAILER_PASS}`,
};